# Generated by Django 5.1.4 on 2025-02-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apelido',
            new_name='apellido',
        ),
    ]
