# Generated by Django 5.1.4 on 2025-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_control_number_alter_customuser_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='control_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=10),
        ),
    ]
